### ISSUE TITLE
Add geofences and newest updates support 

### ISSUE THREAD

**Issue by squiidz** [uber/h3-go#17]
Hi, looking at the C h3 lib a lot of features are lacking in the go version, do you have any plan to support the latest updates ?

**Comment by sbsends** [comment]
Agree with @squiidz. Are there any plans to sync this project?

**Comment by joegilley** [comment]
thanks for the issue! a lot of the missing features have been synchronized from contributions by the community and new support from engineers at uber.  there are still a handful of missing functions before we reach full parity though.  

if there are specific functions that you need, but aren't yet available, I'd love if you could create a new issue with a list of the functions names from the C library you want so they can be prioritized by contributors <3
