### ISSUE TITLE
Indexes don't match (h3-js and h3-go)

### ISSUE THREAD

**Issue by gwuah** [uber/h3-go#34]
Hi, I'm very new to this library and I'm using it in a project i'm working on.
My backend is in go and my frontend is in react.

## Problem.
When I pin-point 2 locations on a map in the same hexagon, I expect them to be have the same index. Which works as expected on the frontend.
But when I index them on the backend, I get 2 different indices.

## Sample Data I'm working with;

```
Location 1
{
    "driver_id": "1",
    "lat": "5.679056546966131",
    "lng": "-0.2408966745733654"
}

Location 2
{
    "lat": "5.6822593911240595",
    "lng": "-0.2415833200811779"
}

Resolution = 8
```

### Aside
So just to test verify my logic, i found the center on of all the indices I had on the backend.
and when I plotted them on the frontend, I noticed they were all in different hexagons even though the initial points were from 1 hexagon.

Picking Coordinate Stage
<img width="636" alt="Screen Shot 2020-05-15 at 4 42 09 PM" src="https://user-images.githubusercontent.com/24861123/82075126-4e099600-96cb-11ea-9424-f1a851de3132.png">

After indexing coordinates and finding the center of the indices
<img width="641" alt="Screen Shot 2020-05-15 at 4 42 30 PM" src="https://user-images.githubusercontent.com/24861123/82075186-65488380-96cb-11ea-82db-8d729e77f12e.png">

Could this be the problem? and If yes, how do I resolve that.
<img width="571" alt="Screen Shot 2020-05-15 at 4 23 49 PM" src="https://user-images.githubusercontent.com/24861123/82073347-a55a3700-96c8-11ea-9e0b-1f456ce2695b.png">

Thanks in advance and great project btw. Helped me a lot

**Comment by gwuah** [comment]
I use the code below to parse the values I receive from the frontend
```
lat, _ := strconv.ParseFloat(data.Lng, 64)
lng, _ := strconv.ParseFloat(data.Lat, 64)
```

**Comment by nrabinowitz** [comment]
Can you clarify what you're showing in the two images? Where do the coordinates of the 3 blue markers come from in each?

**Comment by dfellis** [comment]
> I use the code below to parse the values I receive from the frontend
> 
> ```
> lat, _ := strconv.ParseFloat(data.Lng, 64)
> lng, _ := strconv.ParseFloat(data.Lat, 64)
> ```

Is this actually the code? Because you're assigning `data.Lng` to `lat` and `data.Lat` to `lng` in this example.

**Comment by gwuah** [comment]
Thanks for replying @nrabinowitz 
I just figured out the bug. I was passing lng as latitude and lat as longitude, hence the bug. I'm sorry for notification.
Great Project btw. I love it.

**Comment by gwuah** [comment]
Yeah exactly @dfellis, I didn't notice till i posted it here.
I'll close this now. Sorry for the false alert

**Comment by dfellis** [comment]
No problem! Good luck with what you're working on :)
