### ISSUE TITLE
Build Issue with go mod

### ISSUE THREAD

**Issue by nsehgal** [uber/h3-go#35]
How to build uber h3 go lib with go mod?

**Command**

RUN CGO_ENABLED=1 go build -o appName

**Error** 
github.com/uber/h3-go
exec: "gcc": executable file not found in $PATH

Thanks for the help.

**Comment by joegilley** [comment]
hello! CGO requires a `gcc` (or any CC compiler via `CC=` environment variable) compiler to be available in `$PATH`.  The error you received is telling you that you don't have `gcc`, the default C compiler installed or available in your executables `PATH`.
