### ISSUE TITLE
Obtaining a neighboring indexes from a given cell index around a given radius - m or km

### ISSUE THREAD

**Issue by anjulapaulus** [uber/h3-go#48]
Hi,
Is it possible to get the neighboring indexes from a given cell index around a given radius which is either in metres or kms? I have a usecase which requires that?  It would be helpful if there is another way to obtain them that using haversine.

**Comment by nrabinowitz** [comment]
H3 can approximate this very efficiently - see https://observablehq.com/@nrabinowitz/h3-radius-lookup for some approaches here. One option not included there is to use H3 to get an initial candidate set, then use Haversine or similar to accurately check distance.
