### ISSUE TITLE
error=failed to build for windows_386: exit status 1: package [appname]: build constraints exclude all Go files in [path to app]

### ISSUE THREAD

**Issue by jamiedaniel** [uber/h3-go#51]
When I use the basic template for the .goreleaser.yaml, I get the following error:

error=failed to build for windows_386: exit status 1: package [appname]: build constraints exclude all Go files in [path to app files]
error=failed to build for amd64_v1: exit status 1: package [appname]: build constraints exclude all Go files in [path to app files]

It doesn't matter what I remove - there is always the same error on a different release.

I have read the docs and other sources to no avail. Even on discord which was not active.

**Comment by isaacbrodsky** [comment]
According to https://github.com/uber/h3-go#prerequisites this error can relate to not having CGO enabled. Can you confirm CGO_ENABLED=1 is in your environment? What version of Go, C compiler, and OS are you using?

You mentioned a Discord but I'm not familiar with one for H3. We mostly use the H3 slack linked from uber/h3.
