### ISSUE TITLE
Request for v4 parity 

### ISSUE THREAD

**Issue by jogly** [uber/h3-go#56]
* [x] Vertex mode - thanks to @mojixcoder 
* [ ] Error codes

**Comment by Aditya-Sood** [comment]
hi @jogly, is this issue still valid?

**Comment by jogly** [comment]
@Aditya-Sood yep! vertex mode would be a great first issue if you're interested in contributing!

**Comment by Aditya-Sood** [comment]
hi @jogly, is there anyone else I can reach out to for understanding the context of the issue?

**Comment by mojixcoder** [comment]
Hi @jogly , Can I work on error codes?
