### ISSUE TITLE
Looking for active maintainers, volunteer here!

### ISSUE THREAD

**Issue by zhlc2008** [uber/h3-go#65]
Is there anyone still maintaining this project? Are there any plans to synchronize with https://github.com/uber/h3?

**Comment by ajfriend** [comment]
Unfortunately, we do not have an active maintainer for `h3-go`.

If anyone is interested in helping maintain, please reach out! You can comment on this issue or discuss in Slack listed here: https://h3geo.org/docs/community/tutorials/#community

**Comment by jogly** [comment]
While I'm not personally actively maintaining this repo, several folks have contributed updates which I happily review & release. I like @ajfriend 's invitation for prospective maintainers to volunteer on this ticket so I will leave this open!

**Comment by zachcoleman** [comment]
I'm happy to help review and continue to contribute. With respect to one of the original comments, I have a fork and draft pr #68 to get a head start on the next release and personally to expose experimental features we use at my work.

**Comment by jogly** [comment]
Approved! Sent you an invite @zachcoleman, you can hit me up anytime on our H3 slack if you have any questions.
